# Adder configuration file
# See https://github.com/jrschumacher/adder for documentation

binary_name: testapp
input: docs/commands
output: generated
package: generated
generated_file_suffix: _generated.go
index_format: directory
package_strategy: directory
