version: "2"

run:
  timeout: 10m
  tests: true
  skip-dirs:
    - testdata
    - example/generated
    - cmd/generated

linters:
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - revive
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  
  disable:
    - funlen    # Allow long functions for comprehensive tests
    - gosec     # Allow standard file operations for CLI tool
    - lll       # Allow long lines for templates

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  funlen:
    lines: -1
    statements: 200
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  gocyclo:
    min-complexity: 15
  
  govet:
    check-shadowing: true
    enable-all: true
  
  lll:
    line-length: 200
  
  misspell:
    locale: US
  
  nolintlint:
    allow-leading-space: false
    require-explanation: true
    require-specific: true
  
  revive:
    confidence: 0.8

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - gosec
    
    # Exclude generated files
    - path: ".*_generated\\.go"
      linters:
        - revive
        - lll
        - goconst
    
    # Allow longer lines in templates
    - path: templates\.go
      linters:
        - lll
    
    # Allow file operations in CLI tool
    - text: "G301:|G306:|G304:"
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0