// Code generated by adder. DO NOT EDIT.

package deploy

import (
	
	"github.com/spf13/cobra"
)


// DeployRequest represents the parameters for the deploy command
type DeployRequest struct {
}

// DeployHandler defines the function type for handling deploy commands
type DeployHandler func(cmd *cobra.Command, req *DeployRequest) error

// NewDeployCommand creates a new deploy command with the provided handler function
func NewDeployCommand(handler DeployHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "deploy",
		Short:   "Deploy Commands",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runDeploy(cmd, args, handler)
		},
	}

	// Register flags

	return cmd
}

// runDeploy handles argument and flag extraction
func runDeploy(cmd *cobra.Command, args []string, handler DeployHandler) error {

	// Create request
	req := &DeployRequest{
	}

	// Call handler
	return handler(cmd, req)
}
