// Code generated by adder. DO NOT EDIT.

package example

import (
	
	"github.com/spf13/cobra"
)


// ExampleRequest represents the parameters for the example command
type ExampleRequest struct {
}

// ExampleHandler defines the function type for handling example commands
type ExampleHandler func(cmd *cobra.Command, req *ExampleRequest) error

// NewExampleCommand creates a new example command with the provided handler function
func NewExampleCommand(handler ExampleHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "example",
		Aliases: []string{"ex"},
		Short:   "Example Commands",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runExample(cmd, args, handler)
		},
	}

	// Register flags

	return cmd
}

// runExample handles argument and flag extraction
func runExample(cmd *cobra.Command, args []string, handler ExampleHandler) error {

	// Create request
	req := &ExampleRequest{
	}

	// Call handler
	return handler(cmd, req)
}
